### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by Link2Twenty** [abdonrd/PolymerProjects#12]
Add:
https://www.masseffect.com

Remove:
https://customelements.io

I would have submitted a pull request but I think having lots of pull request for the same file can get messy (feel free to correct me 🙂)

**Comment by abdonrd** [comment]
Thanks @Link2Twenty!

And no, PRs are very welcome! There should be no problem even if there were many PRs.

**Comment by Link2Twenty** [comment]
OK, I've made a PR.
