### ISSUE TITLE
Favicon for aesthetics

### ISSUE THREAD

**Issue by Link2Twenty** [abdonrd/PolymerProjects#44]
I don't know if this is more effort than it's worth but you can add a favicon for each line quite easily, once past the initial hurdle of adding it to all the existing entries.

This has the added benefit of giving you a visual queue as to whether the site is still active or not. Sites without a favicon will display like so: ![invalid](https://www.google.com/s2/favicons?domain=invalid.url)

```
![alt-text](https://www.google.com/s2/favicons?domain=domain.com)
```

**Example:**

|     | Name | Polymer version | [PWA](https://developers.google.com/web/progressive-web-apps/ "Progressive Web App") | Source |
| :-: | :--- | --------------: | :-: | -----: |
| [🔗](https://areafiftylan.nl) | ![AreaFiftyLAN ](https://www.google.com/s2/favicons?domain=areafiftylan.nl/) AreaFiftyLAN | `2.1` | | [Source](https://github.com/AreaFiftyLAN/lancie-frontend) |
| [🔗](https://askapp-ddc29.firebaseapp.com) | ![AskApp ](https://www.google.com/s2/favicons?domain=bitbucket.org/jordanhope/askapp) AskApp | `1.7` | | [Source](https://bitbucket.org/jordanhope/askapp) |
| [🔗](https://www.bithound.io) |  ![bitHound ](https://www.google.com/s2/favicons?domain=bithound.io) bitHound | `1.2` | | |
| [🔗](https://www.bbvaapimarket.com) |  ![BBVA API Market](https://www.google.com/s2/favicons?domain=www.bbvaapimarket.com) BBVA API Market | `1.7` | | |
| [🔗](https://bluemesh.com) | ![BlueMesh ](https://www.google.com/s2/favicons?domain=bluemesh.com) BlueMesh | `1.9` | | |
| [🔗](https://braid.io) |  ![Braid](https://www.google.com/s2/favicons?domain=bluemesh.com) ~~Braid~~ (deprecated) | `1.2` | | |
| [🔗](https://www.catminingexperience.com) |  ![Caterpillar ](https://www.google.com/s2/favicons?domain=www.catminingexperience.com) ~~Caterpillar - MINExpo 2016~~ (deprecated) | `1.6` | | |
| [🔗](https://www.cerberusapp.com) |  ![Cerberus ](https://www.google.com/s2/favicons?domain=www.cerberusapp.com) Cerberus | `1.9` | | |
| [🔗](https://cloudstitch.com) |  ![Cloudstitch ](https://www.google.com/s2/favicons?domain=cloudstitch.com) Cloudstitch | `2.0` | | |

**Comment by abdonrd** [comment]
I like the idea! #45
